#!/bin/bash
#SBATCH --job-name=deepmd-jax
#SBATCH -A m3538_g
#SBATCH -C gpu
#SBATCH -q shared
#SBATCH -t 04:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --mail-type=begin        # send email when job begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-type=fail          # send email when job fails
#SBATCH --mail-user=ruiqigao@princeton.edu

module load python
conda activate deepmd-jax
python -u train.py > outdir/log_water_128_2.out
# python -u train_mp.py > outdir/log_mp_polaron_22.out
# for i in {1..20}; do
#     python -u train_mp_short.py >> outdir/log_mp_multipletest_99_new_0.02.out
# done
# python -u train_mp_ip.py > outdir/log_mp_ip_22.out
# python -u train_mp_water.py > outdir/log_mp_mdsim_water_val.out
# python -u train_water.py > outdir/log_mdsim_water_val.out
# python -u train_mp_lips.py > outdir/log_mp_lips_2nd_2.out
# python -u train_mp_lips.py > outdir/log_mp_lips_22.out
# python -u train_lips.py > outdir/log_lips_4_long.out
# python -u train_exp.py > outdir/log_lips_exp_4.out
# python -u train_exp.py > outdir/log_polaron_exp_1.out
# python -u train_cu.py > outdir/log_cu_12_4.out
# python -u train_mp_cu.py > outdir/log_mp_cu_12_8_4.out
# python -u train_icewater.py > outdir/log_icewater_ip.out
# python -u train_dpse_tio2.py > outdir/log_dpse_tio2_R.out
# python -u train_mp_dpse_tio2.py > outdir/log_mp_dpse_tio2_R.out