#!/bin/bash
#SBATCH --job-name=deepmd-jax
#SBATCH -A m3538_g
#SBATCH -C gpu
#SBATCH -q regular
#SBATCH -t 01:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=4

module load python
conda activate deepmd-jax
python -u simulate.py > log